### ISSUE TITLE
[1.12.1] Crush

### ISSUE THREAD

**Issue by Smartaros** [LakMoore/InfiniTiC#12]
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Infini-TiC (infinitic)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 0
	at me.johz.infinitic.lib.data.MaterialData.integrateMaterial(MaterialData.java:156)
	at me.johz.infinitic.lib.data.MaterialData.preInit(MaterialData.java:84)
	at me.johz.infinitic.InfiniTiC.preInit(InfiniTiC.java:86)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:609)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:604)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:266)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:466)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:377)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297)
	at org.multimc.EntryPoint.listen(EntryPoint.java:162)
	at org.multimc.EntryPoint.main(EntryPoint.java:53)

**Comment by Smartaros** [comment]
script:

{
	"name": "Menril",
	"make": [],
	"textColor": "#FF1EDCE6",
	"whitelist": 
	{
		"oredict": [],
		"ingots": [],
		"nuggets": [],
		"dusts": [],
		"gems": ["integrateddynamics:crystalized_menril_chunk"],
		"blocks": ["integrateddynamics:crystalized_menril_block"],
		"ores": []
	},
	"blacklist": 
	{
		"oredict": [],
		"ores": []
	},
	"fluidData": 
	{
		"color": "#FF1EDCE6",
		"density": 2000,
		"viscosity": 10000,
		"temperature": 1000,
		"luminosity": 10,
		"rarity": "COMMON"
	},
	"canCraftToolForge": true,
	"toolData": 
	{
		"durability": 25,
		"harvestLevel": 0,
		"extraDurability": 10,
		"miningSpeed": 1.5,
		"attack": 3.0,
		"handleModifier": 1.4,
		"handleDurability": 5,
		"color": "#FF1EDCE6",
		"temperature": 200,
		"projectiles": false,
		"drawSpeed": 1.0,
		"range": 1.0,
		"bonusDamage": 0.0,
		"stringModifier": 0.0,
		"shaftModifier": 1.0,
		"bonusAmmo": 0.0,
		"accuracy": 1.0,
		"fletchingModifier": 1.0,
	    "traits": [],
	    "headTraits": [],
	    "handleTraits": [],
	    "extraTraits": [],
	    "bowTraits": [],
	    "stringTraits": [],
	    "projectileTraits": [],
	    "shaftTraits": [],
	    "fletchingTraits": []
	},
	"localizations": 
	[{
		"locale": "en_US",
		"solid": "Menril",
		"liquid": "Molten Menril",
		"bucket": "Menril Bucket"
	}]
}

**Comment by LakMoore** [comment]
Please check that "integrateddynamics:crystalized_menril_chunk" is the correct name for your gem.

I can put in some extra protection to avoid the crash but the real problem is that it cannot find that item.

There should also be a warning in the log about how the item cannot be found.

**Comment by LakMoore** [comment]
Closing as it should be fine now.  Please open a new issue if it is still not working for you.
