### ISSUE TITLE
Crash Report - Default Config Crashes Game

### ISSUE THREAD

**Issue by ghost** [LakMoore/InfiniTiC#28]
With version InfiniTiC-1.12-0.1.42 and forge-14.23.5.2815 the game crashes with the default config provided by the wiki as well as with the custom config created. Json files were used and I used the JSON "validator" website to make sure they were valid/structured properly and all the files came back positive.

(I am registering a content tweaker item [contenttweaker:item_id] if that changes anything, but I doubt it does since Content Tweaker is the first thing that is loaded by FML, so it shouldn't be crashing from the item not existing)

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  WTPlugin (WaitingTime-1.0.1.jar)
  OTGCorePlugin (OTG-Core.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  LoadingPlugin (Reskillable-1.12.2-1.12.3.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 2/18/19 10:41 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Infini-TiC (infinitic)
Caused by: slimeknights.tconstruct.library.TinkerAPIException: [TCon API] Could not register Material "diamond": It was already registered by Infini-TiC
	at slimeknights.tconstruct.library.TinkerRegistry.error(TinkerRegistry.java:951)
	at slimeknights.tconstruct.library.TinkerRegistry.addMaterial(TinkerRegistry.java:129)
	at slimeknights.tconstruct.library.MaterialIntegration.preInit(MaterialIntegration.java:101)
	at lakmoore.infinitic.lib.data.MaterialData.integrateMaterial(MaterialData.java:113)
	at lakmoore.infinitic.CommonProxy.preInit(CommonProxy.java:62)
	at lakmoore.infinitic.client.ClientProxy.preInit(ClientProxy.java:33)
	at lakmoore.infinitic.InfiniTiC.preInit(InfiniTiC.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:624)
	at sun.reflect.GeneratedMethodAccessor2.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:627)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:252)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:467)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 389048640 bytes (371 MB) / 1105199104 bytes (1054 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 5 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6144m -Xms256m -XX:PermSize=256m -XX:-DisableExplicitGC
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2815 24 mods loaded, 24 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                   | Version             | Source                               | Signature                                |
	|:----- |:-------------------- |:------------------- |:------------------------------------ |:---------------------------------------- |
	| LCH   | minecraft            | 1.12.2              | minecraft.jar                        | None                                     |
	| LCH   | mcp                  | 9.42                | minecraft.jar                        | None                                     |
	| LCH   | FML                  | 8.0.99.99           | forge-1.12.2-14.23.5.2815.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | forge                | 14.23.5.2815        | forge-1.12.2-14.23.5.2815.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCH   | otgcore              | 1.12.2 - v7         | minecraft.jar                        | None                                     |
	| LCH   | crafttweaker         | 4.1.14              | CraftTweaker2-1.12-4.1.14.jar        | None                                     |
	| LCH   | jei                  | 4.13.1.225          | jei_1.12.2-4.13.1.225.jar            | None                                     |
	| LCH   | base                 | 3.11.0              | base-1.12.2-3.11.0.jar               | None                                     |
	| LCH   | openterraingenerator | v6                  | OpenTerrainGenerator-1.12.2 - v6.jar | e9f7847a78c5342af5b0a9e04e5abc0b554d69e0 |
	| LCH   | biomebundle          | 5.1                 | Biome_Bundle-1.12.2-v6.1.jar         | None                                     |
	| LCH   | reskillable          | 1.12.2-GRADLE:BUILD | Reskillable-1.12.2-1.12.3.jar        | None                                     |
	| LCH   | mantle               | 1.12-1.3.3.42       | Mantle-1.12-1.3.3.42.jar             | None                                     |
	| LCH   | tconstruct           | 1.12.2-2.12.0.115   | TConstruct-1.12.2-2.12.0.115.jar     | None                                     |
	| LCH   | compatskills         | 1.12.2-1.13.4       | CompatSkills-1.12.2-1.13.4.jar       | None                                     |
	| LCH   | contenttweaker       | 1.12.2-4.9.1        | ContentTweaker-1.12.2-4.9.1.jar      | None                                     |
	| LCH   | ctgui                | 1.0.0               | CraftTweaker2-1.12-4.1.14.jar        | None                                     |
	| LCH   | crafttweakerjei      | 2.0.2               | CraftTweaker2-1.12-4.1.14.jar        | None                                     |
	| LCH   | dimensionaledibles   | 1.3                 | DimensionalEdibles-1.12.2-1.3.jar    | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LCE   | infinitic            | 1.12-0.1.42         | Infini-TiC-1.12-0.1.42.jar           | None                                     |
	| LC    | otgskylands          | 1.0                 | OTG-Skylands-1.12.2-v5.jar           | None                                     |
	| LC    | resourceloader       | 1.5.3               | ResourceLoader-MC1.12.1-1.5.3.jar    | d72e0dd57935b3e9476212aea0c0df352dd76291 |
	| LC    | simpledimensions     | 1.3.1               | SimpleDimensions-MC1.12-1.3.1.jar    | None                                     |
	| LC    | traverse             | 1.6.0               | Traverse-1.12.2-1.6.0-69.jar         | None                                     |
	| LC    | waitingtime          | 1.0.1               | WaitingTime-1.0.1.jar                | None                                     |

	Loaded coremods (and transformers): 
WTPlugin (WaitingTime-1.0.1.jar)
  com.blamejared.waitingtime.core.WTClassTransformer
OTGCorePlugin (OTG-Core.jar)
  com.pg85.otg.forge.asm.OTGClassTransformer
LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  lumien.resourceloader.asm.ClassTransformer
LoadingPlugin (Reskillable-1.12.2-1.12.3.jar)
  codersafterdark.reskillable.base.asm.ClassTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13469 Compatibility Profile Context 21.19.526.1026' Renderer: 'AMD Radeon R7 Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
```

**Comment by LakMoore** [comment]
This is really old. Apologies.
If this is still an issue, please post your json config files so I can test.

**Comment by LakMoore** [comment]
New version released for MC1.12.2.  This should work correctly now.  If not, please post a link to the mod you are using and a pastebin of your json config file.
